### ISSUE TITLE
Unable to use Image Cropper in product document type

### ISSUE THREAD

**Issue by AshleyMedway** [Merchello/Merchello#2121]
When you use the Umbraco Image Cropper element the image is not saved and no error message is shown.

The following error is found in the Umbraco log:

```
 2018-01-20 06:24:18,777 [P12608/D2/T115] WARN  Merchello.Core.ValueConverters.DetachedValuesConverter - Failed to convert property value for Database. Exception: System.Exception: Missing cuid/puid additional data.
   at Umbraco.Web.PropertyEditors.ImageCropperPropertyValueEditor.ConvertEditorToDb(ContentPropertyData editorValue, Object currentValue)
   at Merchello.Core.ValueConverters.DetachedValuesConverter.ConvertEditorToDb(IContentType contentType, KeyValuePair`2 dcv, IDictionary`2 additionalData)
```
I've started a fork and will see if I can fix it :)

**Comment by AshleyMedway** [comment]
fixes #2121
