### ISSUE TITLE
Tried to install Merchello on Umbraco Cloud and it crashed the system

### ISSUE THREAD

**Issue by darrenkras** [Merchello/Merchello#2171]
Tried to install Merchello on Umbraco Cloud and it crashed the system

Message:
An unhandled exception occurred

									
Exception:
System.Reflection.ReflectionTypeLoadException: Could not load all types from "Merchello.FastTrack.Ui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileNotFoundException: Could not load file or assembly 'Merchello.Web, Version=2.6.6484.37120, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Umbraco.Core.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Core.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Core.TypeFinder.FindClassesOfType[T](IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Core.PluginManager.<>c__DisplayClass51_0`1.<ResolveTypes>b__1()
   at Umbraco.Core.PluginManager.ResolveTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, Boolean cache)
   at Umbraco.Core.PluginManager.ResolveTypesInternal(Type baseType, Type attributeType, Func`1 finder, Boolean cache)
   at Umbraco.Core.PluginManager.ResolveTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Core.CoreBootManager.InitializeApplicationEventsResolver()
   at Umbraco.Core.CoreBootManager.Initialize()
   at Umbraco.Web.WebBootManager.Initialize()
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)

**Comment by YodasMyDad** [comment]
Looks like you tried to install FastTrack. Did you install Merchello first?

**Comment by darrenkras** [comment]
I did a search in the plugin directory for Merchello, which brought up the Merchello install but when I went to the details page it did say FastTrack. I figured it was a bundle. Are you meant to install Merchello from the back office?

**Comment by YodasMyDad** [comment]
FastTrack is the starter kit for Merchello. You **must have** Merchello installed first.

**Comment by darrenkras** [comment]
Please look at the screens below. Why would searching for Merchello and finding the Merchello package, then give you a download for FastTrack without Merchello?

 

 

Step 1 – Search for Merchello. Click on first package labelled “Merchello”

 

 

 

Arrive at Merchello screen with no mention of FastTrack

 

 

Click install package and get taken to FastTrack.
