### ISSUE TITLE
Merchello 2.6.0 on Umbraco 7.12, .NET 4.7.1 throws error creating UnitOfWorkProvider 

### ISSUE THREAD

**Issue by benjaminhowarth1** [Merchello/Merchello#2184]
```
2018-10-16 18:36:30,062 [P34128/D2/T1] ERROR Merchello.Web.UmbracoApplicationEventHandler - Initialization of Merchello failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at Merchello.Core.CoreBootManager.SetUnitOfWorkProvider()
   at Merchello.Core.CoreBootManager..ctor(ILogger logger, ISqlSyntaxProvider sqlSyntaxProvider)
   at Merchello.Web.WebBootManager..ctor()
   at Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
```

Going to compile from source to find out why.

**Comment by YodasMyDad** [comment]
I have it working on 7.12.3 will release in next week or so
