### ISSUE TITLE
Current has not been initialized on Merchello.Core

### ISSUE THREAD

**Issue by ivankrzak** [Merchello/Merchello#2203]
Hello ,
Hello, Yesterday guys from hosting migrated customers website to a new Windows server, from then we are getting this error :
> Current has not been initialized on Merchello.Core.EntityCollections.EntityCollectionProviderResolver. You must initialize Current before trying to read it.
[https://wolfpackclth.com/shop](url)

Im getting these logs and cant wrap my head around 

`2018-12-19 18:43:25,715 [P11168/D2/T1] INFO  Merchello.Web.UmbracoApplicationEventHandler - Attempting to initialize Merchello
 2018-12-19 18:43:25,730 [P11168/D2/T1] INFO  Merchello.Web.WebBootManager - Verifying Merchello Database is present.
 2018-12-19 18:43:26,855 [P11168/D2/T1] INFO  Merchello.Core.CoreBootManager - Initializing Merchello GatewayResolver
 2018-12-19 18:43:26,855 [P11168/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Merchello.Core.Gateways.GatewayProviderBase
 2018-12-19 18:43:26,855 [P11168/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Merchello.Core.Gateways.GatewayProviderBase, found 0 (took 9ms)
 2018-12-19 18:43:26,918 [P11168/D2/T1] ERROR Merchello.Web.UmbracoApplicationEventHandler - Initialization of Merchello failed
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket)
   at Umbraco.Core.StringExtensions.DecryptWithMachineKey(String value)
   at Merchello.Core.Persistence.Factories.GatewayProviderSettingsFactory.BuildEntity(GatewayProviderSettingsDto dto)
   at Merchello.Core.Persistence.Repositories.GatewayProviderRepository.<PerformGetAll>d__5.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Merchello.Core.Persistence.Repositories.MerchelloRepositoryBase`1.GetAll(Guid[] keys)
   at Merchello.Core.Services.GatewayProviderService.GetAllGatewayProviders()
   at Merchello.Core.Gateways.GatewayProviderResolver.BuildActivatedGatewayProviderCache()
   at Merchello.Core.CoreBootManager.InitializeGatewayResolver(IServiceContext serviceContext, CacheHelper cache)
   at Merchello.Core.CoreBootManager.Initialize()
   at Merchello.Web.WebBootManager.Initialize()
   at Merchello.Core.MerchelloBootstrapper.Init(BootManagerBase bootManager)
   at Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
 2018-12-19 18:43:26,965 [P11168/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True`

Do you have any suggestions ? 

Thank you

**Comment by ivankrzak** [comment]
there was problem on the server side of things.
thank you eighter way
