### ISSUE TITLE
SMTP Notification on OrderConfirmation throws error

### ISSUE THREAD

**Issue by John-Blair** [Merchello/Merchello#2255]
Merchello 2.7.0: SMTP notification setup , added ordrconfirmation default notification to use 
OrderConfirmation.cshtml which @inherits Merchello.Web.Mvc.MerchelloHelperViewPage<Merchello.Core.Models.MonitorModels.IPaymentResultMonitorModel>

In the umbracoTraceLog.txt file this causes a model binding exception when the notification is triggered after submitforsettlement:
Note: I don't see any attempt to pass an expected IPaymentResultMonitorModel type.

2019-04-11 16:06:37,320 [P12776/D2/T72] ERROR Merchello.Core.Observation.MonitorBase`1[[Merchello.Core.Models.MonitorModels.IPaymentResultMonitorModel, Merchello.Core, Version=2.7.6876.21825, Culture=neutral, PublicKeyToken=null]] - Monitor error: 
Umbraco.Web.Mvc.ModelBindingException: Cannot bind source type M**erchello.Core.Models.MonitorModels.PaymentResultNotifyModel** to model type **Umbraco.Web.Models.RenderModel.**
   at Umbraco.Web.Mvc.RenderModelBinder.ThrowModelBindingException(Boolean sourceContent, Boolean modelContent, Type sourceType, Type modelType)
   at Umbraco.Web.Mvc.RenderModelBinder.BindModel(Object source, Type modelType, CultureInfo culture)
   at Umbraco.Web.Mvc.UmbracoViewPage`1.SetViewData(ViewDataDictionary viewData)
   at System.Web.Mvc.WebViewPage.ConfigurePage(WebPageBase parentPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Merchello.Web.Mvc.ViewRenderer.RenderViewToStringInternal(String viewPath, Object model, Boolean partial)
   at Merchello.Web.Workflow.Notification.RazorFormatter.Format(String viewPath)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Merchello.Core.Gateways.Notification.FormattedNotificationMessage.get_FormatStatus()
   at Merchello.Core.Gateways.Notification.FormattedNotificationMessage.get_BodyText()
   at Merchello.Core.Gateways.Notification.Smtp.SmtpNotificationGatewayMethod.PerformSend(IFormattedNotificationMessage message, IEnumerable`1 attachments)
   at Merchello.Core.Gateways.Notification.NotificationContext.Send(INotificationMessage message, IFormatter formatter, IEnumerable`1 attachments)
   at Merchello.Web.Workflow.Notification.Monitor.RazorMonitorBase`1.OnNext(TModel value)
   at Merchello.Core.Observation.TriggerBase`1.NotifyMonitors(T monitorModel)

**Comment by John-Blair** [comment]
Using the Braintree Transaction payment method when the above notification error occurred.

2019-04-11 16:06:29,531 [P12776/D2/T72] INFO  Merchello.Providers.Payment.Braintree.Services.BraintreeTransactionApiService - Braintree Transaction attempt (SubmitForSettlement) for Invoice FT-22

**Comment by John-Blair** [comment]
Installed nuget package of merchello.core v 2.7.1 - error still present.

**Comment by John-Blair** [comment]
This is now fixed.

The problem was I have a _ViewStart.cshtml file with
@{
    Layout = "~/Views/Shared/master.cshtml";
}
This file has : @inherits UmbracoTemplatePage
which derives from UmbracoViewPage<RenderModel> - causing the error message.

The solution was to add Layout = null;  to both OrderConfirmation.cshtml and OrderShipped.cshtml
<kbd>Pull Request - add this Layout line as default in both those razor files to make it clear no master page is expected!</kbd>

**Comment by John-Blair** [comment]
Clarify:

UmbracoTemplatePage derives from UmbracoViewPage<RenderModel> - hence the problem with cannot convert to RenderModel. Set Layout to null removes the dependency on RenderModel.
