### ISSUE TITLE
EnsureCustomerCreationAndConvertBasket throws NullReferenceException

### ISSUE THREAD

**Issue by ronaldbarendse** [Merchello/Merchello#2266]
As discussed in https://our.umbraco.com/packages/collaboration/merchello/merchello/85584-ysod-after-deleting-logged-in-customer and also reported earlier https://our.umbraco.com/packages/collaboration/merchello/merchello/74547-ensurecustomercreationandconvertbasket-error-on-preview, `EnsureCustomerCreationAndConvertBasket()` throws a `NullReferenceException` when the member can't be found:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Merchello.Web.CustomerContext.<>c__DisplayClass1.<EnsureCustomerCreationAndConvertBasket>b__0(String x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Merchello.Web.CustomerContext.EnsureCustomerCreationAndConvertBasket(ICustomerBase customer)
   at Merchello.Web.Pluggable.CustomerContextBase.TryGetCustomer(Guid key)
   at Merchello.Web.Pluggable.CustomerContextBase.Initialize()
   at Merchello.Web.Pluggable.CustomerContextBase..ctor(IMerchelloContext merchelloContext, UmbracoContext umbracoContext)
   at Merchello.Web.CustomerContext..ctor(UmbracoContext umbracoContext)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Merchello.Core.ActivatorHelper.CreateInstance[T](Type type, Object[] constructorArgumentValues)
```

The affected method is:

https://github.com/Merchello/Merchello/blob/09f99c58fae0dd0fa0217179ddb88c7a0a21979e/src/Merchello.Web/CustomerContext.cs#L112-L123

Looking at this code, it does not handle the following cases correctly:
- `customer` is null - although this probably won't happen, as this method is only called from `TryGetCustomer()`, which already does a null check;
- `MembershipProviderKey()` might return a string that can't be converted to an int - as `GetMembershipProviderKey()` can return an empty string, `Convert.ToInt32()` should be changed to `int.TryParse()`;
- `member` is null - as the `memberId` might be wrong (or just deleted), so just add a null check before accessing `member.ContentTypeAlias`;

So the method would become:
```c#
protected override void EnsureCustomerCreationAndConvertBasket(ICustomerBase customer)
{
	if (!customer.IsAnonymous)
	{
		return;
	}

	var membershipProviderKey = this.MembershipProviderKey(customer.Key);
	if (!int.TryParse(membershipProviderKey, NumberStyles.None, CultureInfo.InvariantCulture, out var memberId))
	{
		return;
	}

	var member = _memberService.GetById(memberId);
	if (member != null && MerchelloConfiguration.Current.CustomerMemberTypes.Any(x => x == member.ContentTypeAlias))
	{
		base.EnsureCustomerCreationAndConvertBasket(customer);
	}
}
```

**Comment by YodasMyDad** [comment]
Thanks

**Comment by ronaldbarendse** [comment]
Just for reference: this is fixed in commit https://github.com/Merchello/Merchello/commit/65914291e8d1cf5178a7184a01a8483c6e92bace 👍
